os: linux
dist: xenial

sudo: required

addon:
  apt:
    update: true

services:
  - docker

env:
  global:
    - IMAGE_NAME='AndroidBuilder'
    - IMAGE_TAG='test'
    - secure: "xCVZa7zt+nbSE81n2y63gAU26rOul0wmhQcECjr4AQzVtadOvmw4VzHB5igTkNvyI/bFFBekjP5oH9GObbfNOMmuWjQTc+RjzwskgZIvk9xZciT0/VfkAswo/IIXxJ1xbeGEyUJ2U57n9EC5Jtl5Mdg1G0PQ1sLNoGARNXLw2I326aTXuy9cs6WS/Q3oc9ShKEAxkbNLDTipcdhj0KB1AyMJaIj4Na/MBZSx8Vjowjh0BDtLVZJVak0NZq770pop9/NV9X/NEB5CT6wjABpRoJv0Vv3W5wTizgMRVNcmjw58iLTzAQHlTR97Q35zFUi7fdI0dZtrIBrkyoDzchPQjDdKJTCrIZKAgsrAprt+oOd4OTzfS1FamAC8myGtHf1/gWYJzcMuIOvF9wR3Iwa5ok3W5iLnWv+J4eWHO57fV6UEllOMtpi1iTWGQtUDk111Dv2ExzHtwzizvmoVykVhwalEIWIqThe4XdWzgMgfCCIsl2Ay/XtMoF9onJaydZpuWCNcL974+UahpjecSmJyNAq47zRJZfgC+P6A3Dh6kkalY7uK+A9caggcVDny2KDu9qEraxHB/wdv55bXBLGTO81qOuc9GHB0vKaZp90HmM8SV7+w6rBdxej2WzuIOiAu5FYvBLAGh+1GrjgcxRZyKsz77BMqYw1er7wcbw2+tcE="
    - secure: "nkeLobNbG2vxAxSAr6jiSB9oJhb4cXhO0W/83c3oNEmXyJBCux8y16RQP4mSq7zZ4S3E/wh/pv9FOc5/Nl9xJ5mF/0bYMwfLLVw4+hrX4DeiiRVlg74vhFJFXQVf3DLhelNDyVn1LqLc7CTewXHUu8RRqtoyFGJO6oKWdRJKnnBU4x1cdic4/lBjfiY2WMw0JXdq3opIy0v/ml1FDaiiK3BLD5JeIfy8Ayyo0Fo7tCfqcwJRg9P5V80qUXYpsmvDphpUddSac1ba37iCu2AX2nZ6Yk6A6QRloYVi2Iaav3DZLLn52UtcYQJIoTygqFgr02SzBkanWYzEzNbxkBI7mVjYHodJO0uI6PxpLmjjBlXXVY/Np5Snwnwu3oQYfjALLUnUzN+7CvxYQiyk4icaXryphgRt8j3kGtTOvPGHZidSXrxcPhMy0Zy6mLR+Hrwf1zNdsCtT6+Du1WrNjEyxZAf7sKHKrJ0t8yTrJDGnGJfQnjU13wxV3CWKXooisZ6qfzW0WLKA9NarnT1CwNkXhTBAeZ4uNQEgE6xSYDBISZUdaeEr+WlmwYax9nOU5O8n8ps8r7uEIe756GpZInAMg7JwJhWXf+kJgTGOLuZAXQmRXb7McLt0rw0Vw6a7ri1Om/kj5nmZRt8MaOwzUurVifGg0jQ7p308LktqmWUh8So="

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWO
  - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

after_success:
  - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 5
